In [780]:
from sklearn.datasets import load_digits



In [781]:
datasets = load_digits()
x = datasets.data
y = datasets.target

In [782]:
x.shape

(1797, 64)

In [783]:
y.shape

(1797,)

In [784]:
#Scaling on the given datasets

In [785]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scaler = sc.fit_transform(x)

In [786]:
#apply pca to reduce dimension

In [793]:
from sklearn.decomposition import PCA

pca = PCA(n_components=61)                                          # fro doing directly ,or counting no of features required ->> you can put pca = PCA(0.95)
pca_x_scaled = pca.fit_transform(x_scaler)

In [788]:
pca_x_scaled.shape

(1797, 61)

In [789]:
pca.explained_variance_ #eigen values

array([7.34477606, 5.83549054, 5.15396118, 3.96623597, 2.9663452 ,
       2.57204442, 2.40600941, 2.06867355, 1.82993314, 1.78951739,
       1.69784616, 1.57287889, 1.38870781, 1.35933609, 1.32152536,
       1.16829176, 1.08368678, 0.99977862, 0.97438293, 0.90891242,
       0.82271926, 0.77631014, 0.71155675, 0.64552365, 0.59527399,
       0.5765018 , 0.52673155, 0.5106363 , 0.48686381, 0.45560107,
       0.44285155, 0.42230086, 0.3991063 , 0.39110111, 0.36094517,
       0.34860306, 0.3195963 , 0.29406627, 0.27692285, 0.258273  ,
       0.24783029, 0.2423566 , 0.217582  , 0.20799593, 0.2000909 ,
       0.18983516, 0.17612894, 0.16875236, 0.15818474, 0.14311427,
       0.13321081, 0.12426371, 0.11932898, 0.11188655, 0.10250434,
       0.09840876, 0.09018543, 0.08246812, 0.07635394, 0.06328961,
       0.05037444])

In [790]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.0134797 , 0.01271931, 0.01165837, 0.01057647, 0.00975316,
       0.00944559, 0.00863014, 0.00836643, 0.00797693, 0.00746471,
       0.00725582, 0.00691911, 0.00653909, 0.00640793, 0.00591384,
       0.00571162, 0.00523637, 0.00481808, 0.00453719, 0.00423163,
       0.00406053, 0.00397085, 0.00356493, 0.00340787, 0.00327835,
       0.00311032, 0.00288575, 0.00276489, 0.00259175, 0.00234483,
       0.00218257, 0.00203598, 0.00195512, 0.00183318, 0.00167946,
       0.00161236, 0.00147763, 0.00135118, 0.00125101, 0.00103696,
       0.00082535])

In [791]:
import numpy as np
arr = np.cumsum(pca.explained_variance_ratio_)  # cumulative frequency
arr

array([0.12033916, 0.21594971, 0.30039385, 0.36537793, 0.41397948,
       0.45612068, 0.49554151, 0.52943532, 0.55941753, 0.58873755,
       0.61655561, 0.64232616, 0.66507919, 0.68735099, 0.70900328,
       0.72814495, 0.74590042, 0.76228111, 0.77824572, 0.79313763,
       0.80661732, 0.81933664, 0.83099501, 0.84157148, 0.85132464,
       0.86077023, 0.86940036, 0.87776679, 0.88574372, 0.89320844,
       0.90046426, 0.90738337, 0.91392246, 0.92033038, 0.92624422,
       0.93195585, 0.93719222, 0.94201029, 0.94654748, 0.95077911,
       0.95483964, 0.95881049, 0.96237542, 0.9657833 , 0.96906165,
       0.97217197, 0.97505772, 0.97782262, 0.98041436, 0.98275919,
       0.98494176, 0.98697774, 0.98893286, 0.99076605, 0.99244551,
       0.99405787, 0.9955355 , 0.99688668, 0.99813769, 0.99917465,
       1.        ])

In [792]:
np.argmax(arr>0.95)+1  #39th index per 95 hoga to plus 1

np.int64(40)